### ISSUE TITLE
Problem s pridavanim do skupiny

### ISSUE THREAD

**Issue by PObdr** [ReCodEx/web-app#100]
Pokusil jsem se na svem dashbardu pridat do skupiny, kterou mam v SISu v rozvrhu. Vypada to, ze se mi to povedlo, ale stejne mi v upozornenich vyskocila hlaska "Server response: Forbidden Request - Access denied".

**Comment by Neloop** [comment]
Zdravim,
z poskytnutych informaci bohuzel nedokazeme zjistit co se presne stalo. Bylo by mozne zjistit alespon priblizny cas kdy k te 403 doslo? Jinak dalsi informace, ktere by se nam mohly hodit bude SIS identifikator skupiny, ke ktere jste se pokousel pripojit a na jake strance se to presne stalo.
S pozdravem Martin Polanka

**Comment by PObdr** [comment]
Nebyla to 403, jen upozornění přímo v recodexu.

Událost vznikla cca minutu před vytvořením issue.

Rozvrhový lístek 17aNPRG013x04 (Java, úterý 9:00, Jančík)
