### ISSUE TITLE
Chybi moznost se odhlasit

### ISSUE THREAD

**Issue by couliquoffe** [ReCodEx/web-app#111]
Po delsi dobe inactivity na ReCodexu (pravdepodobne po expiraci sessionu) je v sidebaru/draweru na miste informaci o uzivateli (`.user-panel`) hlasena chyba:

> nepodarilo se nacist data

a v notifikacich (`.notifications-menu`) je hlaseno:

> access token '...' is not valid

Neni vsak mozne se prihlasit znovu, jelikoz neni mozne se v tuto chvili ani odhlasit.

Jako docasne reseni, je mozne se odhlasit pomoci nejakeho parametru v URL ci neco na ten zpusob?

**Comment by couliquoffe** [comment]
Nasel jsem pullrequest `Automatically logout after token expires #106`, pokud se jedna o stejny problem, pak se pripadne omlouvam za nadbytecne issue.

**Comment by Neloop** [comment]
Zdravim,
ano PR #106 resi presne tuto chybu a mel by byt zaclenen a nasazen jakmile se vyresi jedna malickost. Docasna reseni jsou 2:

1. Mel by fungovat reload stranky v prohlizeci, tudiz F5, pripadne Ctrl+F5, pak by melo dojit k odhlaseni.
2. Pokud vyse uvedene nepomuze, pak je potreba nasadit drastictejsi reseni a to v prohlizeci smazat Cookies a Local Storage (pro FF: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector). Zde si webova aplikace uklada tokeny, po smazani by tudiz mel byt stav stejny jako pred prvnim prihlasenim do aplikace.
