### ISSUE TITLE
Přihlášení mobilní aplikace

### ISSUE THREAD

**Issue by ocamfrla** [ReCodEx/web-app#112]
(Nevím, jestli tento problém patří zde, jelikož se týká mobilní aplikace.)
Stáhl jsem si mobilní aplikaci pro ReCodEx, ale nejde mi se přes ni přihlásit na svůj účet (přes CAS). Zkoušel jsem příhlašení několikrát opakovat, ale pokaždé mě aplikace odmítne s hláškou „This password is incorrect“, ačkoli se stejnými přihlašovacími údaji se normálně přihlásím na svém laptopi přes FF prohlížeč.

**Comment by SemaiCZE** [comment]
Ano, vime o tom. Jiz je reportovano primo u [androidi appky](https://github.com/ReCodEx/android-app/issues/1).
