### ISSUE TITLE
#feedback Body za úlohu ve skupině

### ISSUE THREAD

**Issue by Kechl** [ReCodEx/web-app#131]
Zdravím.
Uvítal bych, kdybych po rozkliknutí skupiny u seznamu úloh, měl napsaný získaný počet bodů a jejich maximum. Usnadnilo by to např. hledání úlohy, která je sice "👍  Succesfull", ale není za ni plný počet bodů.
:)

**Comment by krulis-martin** [comment]
Dobry den,
Rozumim, piseme si do naseho TODO listu.
