### ISSUE TITLE
Nefunguje vyhodnocování úloh

### ISSUE THREAD

**Issue by madvorak** [ReCodEx/web-app#141]
Připadá mi, že přestalo fungovat vyhodnocování v ReCodExu.

Odevzdat řešení lze, progressbar běží (zeleně až do konce), ale pak se nanačte stránka s vyhodnocením, ani když čekám několik minut. Když se podívám znovu přes úvodní stránku, tak body přibyly, ale není vidět odezvdané řešení. Když se z testovacího studenta přepnu na správce skupiny, tak opět nevidím řešení, ale body tam jsou. U úloh, kde bylo jiné nějaké řešení odevzdáno již dříve, se to chová myslím jinak, ale nenačítání stránky s vyhodnocením je problém i tam.

**Comment by SemaiCZE** [comment]
Vyhodnoceni fungovalo, jen neslo zobrazit reseni. Opraveno.
