### ISSUE TITLE
Authentication through CAS fails everytime

### ISSUE THREAD

**Issue by TheSpeedding** [ReCodEx/web-app#150]
What is going on with CodEx? Have been getting this error since morning. I have checked my internet connection obviously, no change.

![ReCodEx login failed](http://www.imagehosting.cz/images/recodex.png)

**Comment by krulis-martin** [comment]
I have just logged in using CAS auth. I am sorry, but I cannot replicate your problem.

**Comment by SemaiCZE** [comment]
ReCodEx should be fully operational the whole day. I cannot replicate the issue either. Also, no server logs seems to give any clue. Is the api at https://recodex.mff.cuni.cz/api/v1 working for you? Or are there any messages in browser console (open via F12 usually)?

**Comment by TheSpeedding** [comment]
I tried to login using three different computers, using different web browswers and different internet service providers. Maybe there's some problem with my ReCodEx account but what I am supposed to do?

API is working. While trying to login using Google Chrome, the console has following output:

bundle.js:39 Refused to connect to 'https://recodex.mff.cuni.cz/api/v1/login/cas-uk/oauth' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' https://raw.githubusercontent.com". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

t.createRequest @ bundle.js:39
bundle.js:39 Refused to connect to 'https://recodex.mff.cuni.cz/api/v1/login/cas-uk/oauth' because it violates the document's Content Security Policy.
t.createRequest @ bundle.js:39
bundle.js:39 Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at bundle.js:39
    at <anonymous>

**Comment by SemaiCZE** [comment]
Thanks for the report, we did some changes with CSP yesterday. It's interesting, that you are the only one with issues. However, the policy is not set as report only, so it should be working now. Try it please and then close the issue.
