### ISSUE TITLE
Submission is counted when file upload dialog fails

### ISSUE THREAD

**Issue by Sejsel** [ReCodEx/web-app#153]
When the file upload dialog fails with an error that triggers the `app.submistSolution.submitFailed` (sic) message, the submission is still counted.

The submission is in the following state afterwards:
> Evaluation Status: Solution was not submitted for evaluation. This was probably caused by an error in the assignment configuration

Since the very same files worked on another attempt, this doesn't seem to be an error in the assignment.

**Comment by Neloop** [comment]
Hello,
thanks for the feedback. There seems to be inconsistency between counting valid submissions in web-app and api. Web-app is performing its own counting which is inaccurate. Please note that this is only displaying issue. Api will still accept submissions even if submission count in web-app will be higher then threshold (Of course till the actual threshold which is computed correctly in api).
We will look at this and send proper count from api to web-app which then only displays it.
