### ISSUE TITLE
"Přidat cvičícího" - no response

### ISSUE THREAD

**Issue by TomHolan** [ReCodEx/web-app#180]
https://recodex.mff.cuni.cz/cs/app/group/f6a69f79-1553-11e8-9de3-00505601122b

Created new group
- button "Přidat cvičícího",
  = nothing changed.

![180219_recodex](https://user-images.githubusercontent.com/36609489/36370020-af74b3c6-155d-11e8-9f20-88946d16ed3b.png)

Helped to change language...

**Comment by krulis-martin** [comment]
Sorry, cannot replicate the problem.

**Comment by TomHolan** [comment]
> Is this still an issue? I just tried it at the production server and it
> worked. If it it still happening please provide more information, like OS,
> browser and if there is something in the browser console.
> Thanks

   Dobry den (snad muzu cesky),

      ne, slo o to, ze po kliknuti
         (stejne jako po pridani studenta do skupiny)
      nenasleduje zadna viditelna zmena,
      dokud nerefreshuju stranku.

      Uz to beru jako feature.

      Tomas Holan

**Comment by SemaiCZE** [comment]
Ano, to my chapem a rozhodne to feature neni. Akorat nedokazem replikovat vas problem, nam se vzdy po pridani studenta ci cvicicho normalne prida a refresh pro jeho objeveni v tabulce treba neni. Muzete prosim zkontrolovat, zda nemate nejake chyby v javascriptove konzoli prohlizece, pripadne zkusit i jiny prohlizec (Chrome)? Diky.

**Comment by TomHolan** [comment]
> Ano, to my chapem a rozhodne to feature neni. Akorat nedokazem replikovat
> vas problem, nam se vzdy po pridani studenta ci cvicicho normalne prida a
> refresh pro jeho objeveni v tabulce treba neni. Muzete prosim
> zkontrolovat, zda nemate nejake chyby v javascriptove konzoli prohlizece,
> pripadne zkusit i jiny prohlizec (Chrome)? Diky.

   Ted to nezkontroluju, az ve skole -
   - ale kdyz o tom vim, tak mi to nevadi
   (protoze nacteni stranky je pomale,
    tak jsem rad, ze se to neopakuje automaticky pokazde).

   Dekuji za odpoved!

   Tomas Holan
