### ISSUE TITLE
assigner OR not-assigned?

### ISSUE THREAD

**Issue by TomHolan** [ReCodEx/web-app#181]
- task assigned to Group
- try to find way how to allow only C# (remove Pascal, not found)
- assigned again the same task

https://recodex.mff.cuni.cz/en/app/group/27210815-1292-11e8-9de3-00505601122b
shows three different informations:
1) Assignments: "There are no assignments." (i.e. NONE assigned task)
2) Students (points}: "0 from 10" (i.e. ONE assigned task by 10 points)
3) Assignments: Those TWO aasignments (of the same task)

![180219_recodex_2](https://user-images.githubusercontent.com/36609489/36381683-aec92578-1586-11e8-9199-6529d1f12d40.png)

**Comment by krulis-martin** [comment]
1) Assignments are not visible to students, so they do not appear in students dashboard. Edit the assignment and make it visible to students.
2) Cannot replicate, you have probably did not set points to both assignments correctly.
3) That is a feature, not a bug.
