### ISSUE TITLE
Joining a group results in an error

### ISSUE THREAD

**Issue by atx** [ReCodEx/web-app#186]
Joining a group results in a bunch of errors as illustrated on the following screenshot

![recodex](https://user-images.githubusercontent.com/3966931/36672565-045c5acc-1b00-11e8-8cc9-7610bcd14f9a.png)

Potentially important info: I am a student from FEL CVUT.

**Comment by krulis-martin** [comment]
It would be much more helpful if you could provide the actual error strings (which are not completely visible on your screenshot) and exact time when the errors happened.

**Comment by atx** [comment]
After pressing the "Join group" button, a POST to https://recodex.mff.cuni.cz/api/v1/groups/fe62c0e7-1a05-11e8-9de3-00505601122b/students/0616847a-1af6-11e8-9de3-00505601122b fails with an 500 error code and the response contains `{code: 500, success: false, msg: "Unexpected Error Exception"}`. Happened today at 14:45 (first tried also today at around ~14:00)

**Comment by krulis-martin** [comment]
Thank you. We will check it out and get back to you.

**Comment by krulis-martin** [comment]
We have found the bug, New version with a fix will be released today.

**Comment by krulis-martin** [comment]
New version has been released a few minutes ago. If it solved your problem, close this issue.
