### ISSUE TITLE
Zmena jazyka sa premietne iba do niektorych textov

### ISSUE THREAD

**Issue by rikiel** [ReCodEx/web-app#188]
Dobry den,
Zmena jazyka medzi CS/EN zmeni iba niektore texty, napr. 2 tlacitka pri sebe maju jedno cesku a druhe anglicku textaciu
![recodex-texty](https://user-images.githubusercontent.com/13640104/36773455-f93a972a-1c59-11e8-830c-a3c5de3acc20.png)
Po zmene na anglictinu su vsetky texty anglicky...

**Comment by SemaiCZE** [comment]
Ahoj,
to neni bug, jen chybejici ceske preklady. Ted mame jeste spoustu starosti s implementaci novych featur a opravou chyb, takze preklady uplne nestihame udrzovat aktualni. Budem radi za kazdy pull request, staci upravit texty v [cs.json](https://github.com/ReCodEx/web-app/blob/master/src/locales/cs.json). Prosime cesky, slovenstinu zatim nemame :D.
Diky :)
