### ISSUE TITLE
Homepage & notification layout absolutely broken in MSEdge

### ISSUE THREAD

**Issue by petrroll** [ReCodEx/web-app#189]
The website is absolutely broken in MSEdge:

![image](https://user-images.githubusercontent.com/1764721/36786098-6a9c5720-1c85-11e8-983c-60c52a9f0c35.png)
![image](https://user-images.githubusercontent.com/1764721/36786111-739a4396-1c85-11e8-9b22-528485878c5a.png)

Microsoft Edge 41.16299.248.0
Microsoft EdgeHTML 16.16299

**Comment by SemaiCZE** [comment]
Hi,
I don't have Edge so ReCodEx is not tested against it. However I asked a friend and he said the page renders fine with the same versions as you report. Please try to clear your browser cache and local storage first and then make another try. If the issue persists, try to find errors in javascript console and network requests (hope that Edge has support for this).

**Comment by petrroll** [comment]
I've tried accessing we website in private mode (shouldn't keep anything from previous visits) and the issue still persists. 

Console errors: 
![image](https://user-images.githubusercontent.com/1764721/36787611-06bd9f88-1c8b-11e8-990a-781a7048bfac.png)

Network requests (seem fine):
![image](https://user-images.githubusercontent.com/1764721/36787658-2263094e-1c8b-11e8-9861-d6588894cbc0.png)

BTW: This could be useful: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by krulis-martin** [comment]
Sorry, at present time, we do not have time to support other browsers than Firefox and Chrome.

**Comment by petrroll** [comment]
No problem :), it works-ish anyway.

**Comment by SemaiCZE** [comment]
We tracked down your problem. Your browser refused to download Bootstrap CSS, because someone is trying to push a modified version to you - we have an integrity check as suggested by official documentation.

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
```

This seems to be just broken Edge browser. If you cannot use a different browser, please try this (which is taken from [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15111126/)):

```
Then I went to one of my two machines where the problem
was still happening and in Edge under Settings, Clear Browsing
Data I selected only “Cached data and files” and cleared.
After this, my 3 plug-ins were working again.
```

**Comment by Neloop** [comment]
Can you please confirm that this is still an issue?

**Comment by petrroll** [comment]
Yep, it's still an issue. Clearing Browser Data didn't help. 
I suppose the Edge with fix will come in next feature update.

**Comment by Neloop** [comment]
Ok, closing for now... interestingly in my Edge (which should be same as yours) the page is working... strange

**Comment by petrroll** [comment]
It's fixed in Edge from Spring Creators Update (1803)

**Comment by krulis-martin** [comment]
Thank you for the information.
