### ISSUE TITLE
registrace přes CAS nefunguje s defaultní rolí mimo MFF

### ISSUE THREAD

**Issue by tomasmcz** [ReCodEx/web-app#191]
Když jsem se pokoušel registrovat účet přes CAS, ReCodEx mi tvrdil, že nejsem student ani zaměstnanec MFF, což bylo poněkud matoucí (jsem obojí). Po přenastavení defaultní role v SISu (kde jsem měl nastavené své další studium na FF) na studium MFF se registrace podařila.

**Comment by krulis-martin** [comment]
Dobry den,
prihlaste se prosim zde: https://webik.ms.mff.cuni.cz/~krulis/cas/ (idealne s tou roli, ktera vam nefungovala) a poslete nasledny dump vsech atributu nebo jejich screenshot na recodex@ksi.mff.cuni.cz. Podivame se na to,

**Comment by krulis-martin** [comment]
Bohuzel se nam nedari najit pricinu. Zvysili jsme uroven detailu logovani, mohl byste se prosim zkusit znovu registrovat na testovaci prostredi (https://recodex-test.ms.mff.cuni.cz/}, tam je kopie dat z ostreho prostredi, ale vas ucet jsem smazal. Btw. pokud to nestihnete dnes, dejte vedet, kdy byste mohl, data se kazdou noc obnovuji.

**Comment by tomasmcz** [comment]
Server response: User is already registered using 'cas-uk'.

**Comment by krulis-martin** [comment]
OK, moje chyba, nechal jsem tam externi vazbu. Zkuste prosim jeste jednou. (ciste pro kontrolu, predpokladam, ze vase UKCO je 72035915)

**Comment by tomasmcz** [comment]
Teď se účet bez problémů vytvořil.

**Comment by krulis-martin** [comment]
Bohuzel my jsme nic nemenili (krome logovani). Tj. musim predpokladat, ze nam CAS o vas pred tim nedal uplnou informaci. Dekujeme za testovani, pokud se to znovu neobjevi pri prihlasovani, tak pro zatim uzaviram.
