### ISSUE TITLE
Nelze vytvorit lokalni ucet

### ISSUE THREAD

**Issue by tynovsky** [ReCodEx/web-app#193]
Na strance https://recodex.mff.cuni.cz/cs/registration nelze vytvorit lokalni ucet.

V dokumentaci se pise, ze bych si mel moci vybrat mezi prihlasovanim heslem a prihlasovanim pres CAS. Moznost zadat heslo ale nenachazim. Jak mam postupovat? Formular "Create ReCodEx account" zminovany v dokumentaci jsem nenasel.

**Comment by SemaiCZE** [comment]
Lokalni ucet v aktualni MFF instanci vytvorit nelze, protoze je treba aby uzivatele byli spravne napojeni pres CAS na SIS a tim padem i na jejich rozvrh. Je mozne k CAS uctu vytvorit i heslo pro lokalni prihlaseni, to se provadi na strance nastaveni uzivatele.
