### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by stodolovak** [ReCodEx/web-app#197]
Dobrý den, 
vzhledem k tomu, že recodex je nasazen zatím asi 2-3 semestry, chtěla bych upozornit na velmi obtěžující jev, který se stane, když je student přihlášen do více skupin (což se nektěrým stalo třeba až teď v tomto semestru). Po přihlášení (či po kliknutí na "Přehled") se vždy zobrazí úplně všechny skupiny, do kterých jsem přihlášená. Nejen, že se to velmi dlouho načítá, navíc musím ještě hledat tu jednu skupinu, která je pro mě tento semestr relevantní. Skupiny se řadí vždy úplně jinak. Reálně u nás prváků určitě nastane situace, že budeme přihlášení třeba do 7 skupin a to už bude úplný horror. Vím, že se dá ze skupiny odejít, ale to z archivačních důvodů dělat nechci - budu se na ty úlohy třeba někdy chtít podívat. 

Nemohli by se ty skupiny tedy automaticky po semestru nějak archivovat? Představuji si, že po přihlášení by se mi ukázaly jen skupiny tohoto semestru a ty další by byly přístupné například po roztažení nabídky "SIS Courses - Student".

Děkuji,
Kateřina Stodolová

**Comment by SemaiCZE** [comment]
Zdravim,
ano, toto mame v planu. API jiz umi u kazde skupiny uchovavat flag zda je archivni, ale na implementaci do web-app se nedostaneme drive nez po vydani pristi verze. Kazdopadne pristi semestr by se jiz archivni skupiny zobrazovat nemely. Plan je, ze vsechny stare skupiny se budou archivovat za oba semestry v lete pred zacatkem noveho akademickeho roku.
Diky za feedback.

**Comment by krulis-martin** [comment]
Dobry den,
skupiny jiz maji implementovan archivacni priznak, zatim jsme nemeli cas upravit uzivatelske rozhrani, aby ho bylo mozne vyuzit. Stejne tak mame v planu vylepsit prehledovou stranku a upravit poradi, ve kterem se skupiny zobrazuji. 
Dale bych chtel podotknout, ze byt v 7 skupinach v jednom semestru uz neni uplne normalni situace. Ve vetsine pripadu se ocekava, ze 1 cviceni/predmet odpovida 1 skupine a ReCodEx se v tuto chvili pouziva (z predmetu pro 1. rocnik) pouze na Programovani I a II. Jestli se divam spravne, tak jste celkem ve 3 skupinach za oba semestry. Pokud by snad nektery cvicici mel tendenci zakladat prilis mnoho skupin pro jedno cviceni, zkuste mu tento problem vysvetlit.
