### ISSUE TITLE
Nelze se přihlásit přes CAS

### ISSUE THREAD

**Issue by domestomas** [ReCodEx/web-app#225]
## Issue Description

Po pokusu o autentizaci přes CAS se zobrazí: 
"Server response: The ticket 'ST-446-pciaHelBwYB22FxF5tOp-cas.cuni.cz' cannot be validated as the response from the server is corrupted or incomplete."

## Environment

Linux, Chrome

**Comment by krulis-martin** [comment]
Dobry den,
to je proto, ze CAS ma opet vypadek a presel na zalozni sluzbu, ktera je ve verzi CAS 3. ReCodEx potrebuje verzi 4.2, aby dostal spravne vsechny udaje. Vypadky jsme jiz urgovali spravci CASu, slibil, ze s tim neco udela. Ted nezbyva, nez chvili pockat, obvykle to netrva dlouho, nez se nahodi aktualni verze CAS. Vic s tim my neudelame.
