### ISSUE TITLE
V tabulce "Students and Their Results" vedou odkazy na úlohy do administrace

### ISSUE THREAD

**Issue by shulda** [ReCodEx/web-app#227]
## Issue Description

Dtto, jde o přístup ze studentského účtu. Žádná uživatelská data mi to nezobrazí (jen to naháže asi sto upozornění "Forbidden Request - Access denied). Když chci stáhnout nejlepší řešení, tak to také správně nabídne jen prázdný soubor, do "Edit assignment settings" se dostat můžu a měnit nastavení jsem nezkoušel, nechci nic rozbít.

## Steps to Reproduce

1. Přihlašte se do Recodexu pod uživatelským účtem
2. Otevřete hlavní stránku nějaké skupiny
3. Najděte část "Students and their results" a klikněte na název libovolné úlohy v záhlaví tabulky.

**Comment by SemaiCZE** [comment]
Zdravim,
o chybe vime, ale jedna se pouze o vizualni problem, dane tlacitko nema byt videt studentum. Jelikoz prava kontroluje API, tak nedostanete zadna data, ktera nemate pravo videt. Ani ulozeni by se vam nepodarilo. Oprava bude nasazena s pristi verzi.
