### ISSUE TITLE
[Feature request] Indicate correctly evaluated task after deadline differently to wrongly evaluated

### ISSUE THREAD

**Issue by petrroll** [ReCodEx/web-app#229]
ReCodex shows valid after-deadline submissions the same way as wrong submissions. While it's correct from the "points received" point of view a distinction (e.g. yellow thumb up) would be very useful. 

Also, the tooltip is slightly misleading. It should say "Correct solution submitted after deadline" or something. 

![image](https://user-images.githubusercontent.com/1764721/39826480-26ee94e0-53b5-11e8-9ad4-abcab37b4e80.png)

**Comment by krulis-martin** [comment]
Yes, current icon preview for each assignment is very brief and may be somewhat misleading. I am planning to improve these hand-signs eventually, but we have still some tasks with higher priority, so I make no promises on exact time frames.

**Comment by SemaiCZE** [comment]
However, if you have some time and send us a small PR, you could become a contributor. You know, procrastination between exams can result in many PRs ;).
