### ISSUE TITLE
Already submitted always shows 0

### ISSUE THREAD

**Issue by rzikm** [ReCodEx/web-app#278]
## Issue Description

When viewing students solutions for an assignment, the label Already submitted always shows 0, regardless of number of submitted solutions

## Environment

MFF recodex

## Steps to Reproduce

1. create an assignment
2. as a student: submit a solution
3. as a teacher, look at submitted solutions count

## Expected Behaviour

Already submitted shows 1 (or more, based on number of solutions submitted)

## Actual Results

Already submitted shows 0, see screenshot

(from https://recodex.mff.cuni.cz/en/app/assignment/c8ee2f7d-cff4-11e8-a4be-00505601122b/user/d0ab45f1-b253-11e7-a937-00505601122b)
![image](https://user-images.githubusercontent.com/32671551/47285245-81b53480-d5ea-11e8-993e-1dee3980c6f8.png)

**Comment by Neloop** [comment]
Bug confirmed and assigned to our task tracking system. Will be solved in one of next releases.

**Comment by krulis-martin** [comment]
The table was slightly redesigned. The mentioned value was for students to see, how many times they can submit their solutions (not for the teacher). Released in 1.14.0.
