### ISSUE TITLE
Progress bar green despite submission failing

### ISSUE THREAD

**Issue by IAmWave** [ReCodEx/web-app#287]
## Issue Description

I submitted a solution and "solution is being evaluated" progress bar ended up being entirely green. Despite this, the solution was not accepted; the verdict was WA.

An example of a submission where this happened is [here](https://recodex.mff.cuni.cz/en/app/assignment/7a361a00-f1b2-11e8-b0fd-00505601122b/solution/0be1d784-0175-11e9-b0fd-00505601122b). The task is `reinforce_with_baseline` from the Deep Reinforcement Learning group.

## Environment

- OS: MacOS Mojave 10.14.2
- Browser: Firefox 64.0

## Steps to Reproduce

1. Submit a WA solution
2. Observe progress bar

## Expected Behaviour

Red parts in the progress bar

## Actual Results

Fully green progress bar

**Comment by krulis-martin** [comment]
Thank you for the feedback. Actually, this is not a bug in ReCodEx. The author of the exercise provided his own judge, which yielded OK status (hence green progress bar), but awarded zero points (hence failed test displayed in the results). I suggest you ask the teacher of Deep Reinforcement Learning course, whether this is intent or mistake.
