### ISSUE TITLE
Second deadline was almost 50 years ago

### ISSUE THREAD

**Issue by IAmWave** [ReCodEx/web-app#293]
Not sure which repo to put this into.

## Issue Description

In the deadline reminder email

"Your assignment 'walker' in the group 'Deep Reinforcement Learning' has a first deadline on 6.1.2019 22:59 and a second one **on 1.1.1970 00:00**. This email is just a reminder that these dates are nearing and you have not submitted any solution yet. "

## Expected Behaviour

The second deadline with a clearly wrong/default value should not be shown.

## Actual Results

It was shown.

**Comment by Neloop** [comment]
Thanks for your bug report.
The emails in ReCodEx in general are not solved ideally at the moment, there is pull request which is addressing mainly localization [https://github.com/ReCodEx/api/pull/264](https://github.com/ReCodEx/api/pull/264), but also other email related issues. We will try to integrate repairs of your issue in this pull request and release new and improved emails in (hopefully) next release of our `api`.

**Comment by Neloop** [comment]
Fixed by https://github.com/ReCodEx/api/pull/264, will be included in next ReCodEx release.
