### ISSUE TITLE
non MFF-student account

### ISSUE THREAD

**Issue by zolotarovgl** [ReCodEx/web-app#314]
## Issue Description

Is it possible to create ReCodEx for a student without MFF affiliation? I have CAS account, but  it's from another faculty. 

I would appreciate any help with this issue. 

## Steps to Reproduce

1.
2.

**Comment by krulis-martin** [comment]
Actually, this is not an issue of the software itself, so I am closing it. If you have trouble registering an account, you should have contacted the teacher of your course where ReCodEx is required and he/she should have told you to contact the administrator (recodex@mff.cuni.cz). So write an email to this address and do not forget to mention which teacher has failed to give you this information.
