### ISSUE TITLE
Edit box for solution comments is too small

### ISSUE THREAD

**Issue by gollux** [ReCodEx/web-app#320]
## Issue Description

Edit box for attaching "Comments and Notes" to a solution starts with one line of text and it is automatically enlarged as I type. However, if I insert a lot of text by pasting it from clipboard, the edit box remains small.

## Environment

Debian Linux (Stretch), Google Chrome 73.0.3683.75.

**Comment by Neloop** [comment]
Thanks for bug report!
We'll try to look into it and fix it to behave correctly

**Comment by krulis-martin** [comment]
Solved. Solution will become available with the next release (coming up soon).
