### ISSUE TITLE
Easy path from table of results to solution details

### ISSUE THREAD

**Issue by gollux** [ReCodEx/web-app#321]
When I view the "Students and Their Results" table on the group overview page, I frequently wonder why the particular submission got so few points. However, it is quite hard to get from the table of results to the particular submission.

It would be nice to make clicking on the number of points lead to the page with submission details.

**Comment by Neloop** [comment]
Thanks for feature request!
As of now, there are some plans to improve solutions table, for example adding option to see best solution altogether (even one after the deadlines), better appearance of the table or as you stated easy path from the table to solution details.
But it might take a while, it is still in analysis phase and we want to bring these features all at once...

**Comment by krulis-martin** [comment]
There were several upgrades which basically fulfill the requested functionality. I am closing the issue.
