### ISSUE TITLE
Use more sensible date format

### ISSUE THREAD

**Issue by gollux** [ReCodEx/web-app#330]
When entering deadlines for assignments, the web app requires time in 12-hour format. A 24-hour format would be much more practical. (BTW, did you consider using ISO 8601 date format [YYYY-MM-DD]?)

**Comment by SemaiCZE** [comment]
Date format depens on selected locale, try to switch to `cs`. I think we don't want to support configurable date format (per user), but we may change the locale defaults. We'll discuss that, thanks for your report.

**Comment by krulis-martin** [comment]
Well 24-hour time format has my support too, I shall address it.

The date format is slightly more complicated, as some people might prefer traditional Czech format d.m.Y over ISO format and I am not in favor of overriding the format for English locale and leaving it for Czech locale. I shall discuss this with Lenka to see, what is the sentiment among the users.

**Comment by krulis-martin** [comment]
After due consideration, we will change the hour format (24 hours should be enough for everyone). However, we have decided to keep the date format consistent with the selected locale (i.e., `m/d/Y` in case of `en` locale). The change will be available with the next release.
