### ISSUE TITLE
Main menu isn't opening on phones

### ISSUE THREAD

**Issue by JanPalasek** [ReCodEx/web-app#350]
## Issue Description

Menu on the main ReCodEx page (https://recodex.mff.cuni.cz/) cannot be opened on a mobile phone and therefore users cannot log in.

![screenshot](https://user-images.githubusercontent.com/26582151/66482077-79c3fe00-eaa2-11e9-8566-0c1cdf6a495d.png)

Screenshot shows that menu button is pressed but the menu is not displayed.

## Environment

iPhone SE
Xiami A2

## Steps to Reproduce

1. Go to https://recodex.mff.cuni.cz/
2. Try to open menu (three lines above another) to sign in

## Expected Behaviour

Menu will open.

## Actual Results

Nothing happens, menu doesn't open and I can't log in.

**Comment by krulis-martin** [comment]
New release is out, we have fixed the button. However, I must point out that we do not have the menpower to test nor try to support mobile environments, so we cannot guarantee that the app will fully work on a cell phone or a tablet...
