### ISSUE TITLE
Getting email notifications for archived courses

### ISSUE THREAD

**Issue by LukasCaha** [ReCodEx/web-app#354]
## Issue Description

I am getting notifications for deadline of assignments for Programming I and II which I took last year. I remember these assignments being due in next year on purpose.

## Expected Behaviour

I would expect you can not get notification from archieved course.

**Comment by krulis-martin** [comment]
Well, there is no legitimate purpose for having a deadline next year.
Nevertheless, ReCodEx must support idiotic teachers as well, so I will look into this bug...

**Comment by krulis-martin** [comment]
I have fixed the bug, the fix will appear in the next release...
