### ISSUE TITLE
Wrong link in verification e-mail

### ISSUE THREAD

**Issue by petrkutalek** [ReCodEx/web-app#390]
## Issue Description

When a new account is created user's email address is not verified. ReCodex automatically sends a verification e-mail containing a link to the recodex page, that validates user's  e-mail address.

However forementioned link is wrong as it contains double slash after hostname. Thus destination URL does not exist (HTTP error 404). `https://recodex.mff.cuni.cz//email-verification?eyJ0eXAiOiJKV1…` should be `https://recodex.mff.cuni.cz/email-verification?eyJ0eXAiOiJKV1…`

I manually corrected address in my browser and it worked all right. My e-mail address is now verified.

## Environment

Version 85.0.4183.121 (Official Build) Arch Linux (64-bit)

## Attachments

 * [email payload in MIME format (TXT and HTML)](https://github.com/ReCodEx/web-app/files/5271734/email_mime.txt)

**Comment by krulis-martin** [comment]
Fixed.
