### ISSUE TITLE
CAS UK SSO not working

### ISSUE THREAD

**Issue by me2d09** [ReCodEx/web-app#392]
## Issue Description

When I try to use CAS for signing into ReCodEx it produces following error:
`2020-09-25 8:08 Signing to ReCodEx using UK-CAS authentication process failed. This usually means that you either do not have an account in ReCodEx yet, the account is disabled, or binding between your account and CAS identity has not been created.`

## Environment

Firefox @ Win10, CAS account 69074999 with roles: 
- Faculty of Mathematics and Physics, faculty
- Faculty of Mathematics and Physics, staff
- Faculty of Mathematics and Physics, member

## Steps to Reproduce

1. Click Authenticate through CAS
2. Fill in login details to cas page

## Expected Behavior

Login to ReCodEx

## Actual Results

![image](https://user-images.githubusercontent.com/7137805/94232613-af0d6a00-ff06-11ea-9fe8-31ded0f95d8b.png)

**Comment by krulis-martin** [comment]
This is NOT a bug in ReCodEx. Contact technical support at recodex@mff.cuni.cz.
