### ISSUE TITLE
feature request: ICS export with deadlines of assignments

### ISSUE THREAD

**Issue by petrkutalek** [ReCodEx/web-app#393]
no issue at all, just a feature request

It would be nice if ReCodEx could provide a unique unauthenticated link with ICS export of deadlines of assignments for a particular user (just dates). I could mention the ICS export of class schedule in IS UK as an example.

Student then could subscribe that ICS link as a calendar into her calendar app (e.g. O365) and not to miss any deadline.

**Comment by krulis-martin** [comment]
Yes, it would.

**Comment by petrkutalek** [comment]
FYI: I have implemented [quick and dirty solution](https://gist.github.com/petrkutalek/b40919eff8c88f279a3f33a9b93f5751) utilizing ReCodEx API. I run it for several weeks now and it works flawlessly.

**Comment by richard-hajek** [comment]
@petrkutalek Your quick and dirty solution seems to be also a missing solution, would you mind uploading it again?

**Comment by krulis-martin** [comment]
Implemented.
