### ISSUE TITLE
Feature Request: Let supervisor see detailed test description for assignments

### ISSUE THREAD

**Issue by kliberf** [ReCodEx/web-app#395]
As a supervisor in a group, but non-owner of an assignment, I am able to see sections *Tests and Scoring* and *Supplementary Files* within assignment test configuration. I am however unable to see how are tests being run (i.e. command line arguments). If I duplicate the assignment, I am able to see (and modify) anything regarding tests configuration.

Would it be possible to provide read-only display of tests configuration even for non-owner?

**Comment by krulis-martin** [comment]
Yes. Will do.

**Comment by krulis-martin** [comment]
Solved. Will be available in next release (planned soon).
