### ISSUE TITLE
502 Proxy Error after assignment deletion

### ISSUE THREAD

**Issue by TomHolan** [ReCodEx/web-app#402]
## Issue Description

When group supervisor refreshes page in browser after succesfull assignment deletion, 
it waits couple of seconds and finally show the message

    Proxy Error
    The proxy server received an invalid response from an upstream server.
    The proxy server could not handle the request GET /app/assignment/e917c528-4ff8-11eb-a1a9-005056ad4f31/edit.
    
    Reason: Error reading from remote server

## Environment

Win10, Chrome.

## Steps to Reproduce

1. Edit assignment settings
2. Delete the assignment
3. Refresh browser page

## Expected Behaviour

Expected behaviour would be some message or return back to the page of the group.

## Actual Results

Long waiting and a message after.

![Snímek obrazovky 2021-01-06 112734](https://user-images.githubusercontent.com/36609489/103764883-93911f80-501c-11eb-9b4c-5659850d767f.jpg)

**Comment by krulis-martin** [comment]
Solved quite some time ago (definitely working in 2.0.0), closing the issue.
