### ISSUE TITLE
Feature Request: Improve UX for commenting on particular piece of code

### ISSUE THREAD

**Issue by rzikm** [ReCodEx/web-app#404]
As a supervisor, I would like to comment on specific lines of the submitted source code, e.g., when student uses a particularly bad construction or manually implements something which is already available via standard libraries. The current system allows commenting on the solution as a whole, but in order to comment on a particular line of code, I need to close the editor, write the comment, and reference the offending code by filename and line number. Students probably face similar problems when trying to match the comment to the source code, because by opening the editor, they hide the comment section....

Ideally, I'd like the commenting functionality like GitLab or GitHub have on Merge/Pull request comments. Since I would use that feature a lot, I don't mind working on it myself. But since it is a rather large change, it should be discussed before I drop a thousand-line PR.

**Comment by krulis-martin** [comment]
Yes, that is definitely on our todo list. Lenka Forstova is in charge of prioritization and in consolidation of feature requests, I suggest talking to her first. We also need to decide how/whether these comments will be integrated with regular (submission) comments and how to display them usefully in timelines (when user resubmits new solutions of an assignment).

**Comment by krulis-martin** [comment]
The first version of code reviews was implemented in the current release.
