### ISSUE TITLE
Feature request: Dark mode

### ISSUE THREAD

**Issue by yagarea** [ReCodEx/web-app#437]
It would be nice to be able to set native dark mode in recodex settings.

**Comment by krulis-martin** [comment]
I am sorry, but this is not a simple matter of adding one css class. Given the vast list of feature requests which are far more important, this will not be prioritized any time soon (i.e., I am closing this issue).

**Comment by Teyras** [comment]
@yagarea May I suggest the darkreader addon for chrome-based browsers?
