### ISSUE TITLE
Feature request: Show total points below the list of assignments in group detail

### ISSUE THREAD

**Issue by VL-CZ** [ReCodEx/web-app#446]
## Issue Description

Hello, 
as a student, I think it would be nice to see **total points** below the list of assignments on *group detail* page. 
Currently, I'm member of a group of about 100 people and we can see other students' results. To see my total points, I need to scroll down the *Students and Their Results* table / use Ctrl+F to find myself there.

## Expected Behaviour

When I go to *group detail*, I see my total points below the list of assignments.

## Actual Results

When I go to *group detail*, my total points are shown in *Students and Their Results* table. If we can see other students' results, I need to manually find myself there.

**Comment by jiri-skrobanek** [comment]
I would say maybe putting first or highlighting the current user in the 'Students and their results' section would be useful extremely useful. You should definitely prioritize this. This feature is not hard to implement and its not like you at recodex have more pressing issues to address (looking at you 'Visualization of points limits and corresponding deadlines' -- not grammatical in English by the way)

Also the loading of student results themselves is suspiciously slow. Had I not known any better about the authors, I would even guess that it is not cached, but a SQL query runs on some huge table every single time someone loads the page.

**Comment by krulis-martin** [comment]
Highlighting current user in students results will be implemented soon.

We have no intention of optimizing loading of results table at this point, nor to employ any form of caching which would be very complicated.

**Comment by VL-CZ** [comment]
Hello,
highlighting is definitely useful for smaller groups. However, I'm not sure about the large ones. 
As I mentioned before, I'm in a group of > 100 students and highlighting probably won't help me much, since I'd need to scroll down the table anyway (which is kind of uncomfortable)

I'd very appreciate if **my total score was displayed**:
- eithter below the list of assignments
- or in the first row of the table (as Jiri suggested)

**Comment by krulis-martin** [comment]
This was solved by highlighting the row of logged-in user and by adding a button to hide everyone else.

There are more elaborate plans in motion for group-points overhaul, this is the best we can do for now.
