### ISSUE TITLE
Multiple whitespace characters in Markdown inline code are rendered as one

### ISSUE THREAD

**Issue by sorashi** [ReCodEx/web-app#449]
Teachers often use inline code in Markdown to define expected inputs and outputs in assignments. The problem is, that unlike multi-line code blocks (which also add `<pre>`), inline code only translates into `<code>`.

A teacher inputs

```md
output: `a      b`
```

Which is rendered as

output: `a b`

This has happened to me (a student) multiple times throughout my 5 semesters of study. Teachers expect the white-space to be persisted in inline code mode. As such, I think that this is undesired behavior for this project, where white-space has a lot of significance.

However, note that this behavior is in compliance with the CommonMark standard and thus it is **not an issue with the `markdown-it` package** you're using.

What I want to point out though, is this note from [example 337](https://spec.commonmark.org/0.30/#example-337) of the CommonMark standard:

> Note that browsers will typically collapse consecutive spaces when rendering &lt;code&gt; elements, so it is recommended that the following CSS be used:
> 
> ```css
> code{white-space: pre-wrap;}  
> ```

Adding this CSS would **fix the aforementioned problem** with assignments.

**Comment by krulis-martin** [comment]
Done. This will appear in the next release.
