### ISSUE TITLE
Bad icon positioning in solutions list

### ISSUE THREAD

**Issue by zdenecek** [ReCodEx/web-app#475]
## Issue Description

When I added a note to one of my solution, it broke the view of the solution in the "Submitted solutions" list. See image:

![grafik](https://user-images.githubusercontent.com/11601685/198031267-aaa57e35-53b0-4053-a33e-dd1a6c511ecb.png)

## Environment

I tried it on both up-to-date Firefox and Chrome, the issue is with styling.

## Steps to Reproduce

1. Submit a solution to any task
2. Add a note to that solution
3. Look at Submitted solutions in Assignment view

## Expected Behavior

Thumbs up/down icon aligning to the top, or middle but not including the note.

## Actual Results

Thumbs up/down icon with middle align, partly covering the note.

**Comment by krulis-martin** [comment]
Thanks, for the report; however, I have just solved this recently (so I am going to close this issue). Please, wait for the next release which will be (with any luck) this weekend.
