### ISSUE TITLE
Solution being evaluated is reported as deleted attempt

### ISSUE THREAD

**Issue by jiri-skrobanek** [ReCodEx/web-app#476]
## Solution being evaluated is reported as deleted attempt

I submitted 1 solution to an assignment and recodex states there was 1 attempt plus 1 attempt by deleted solutions. See screenshot for details.

https://postimg.cc/fVhjqcgP

## Environment

Obviously irrelevant

## Steps to Reproduce

1. Submit a long-running solution

**Comment by krulis-martin** [comment]
Reproduced.

**Comment by krulis-martin** [comment]
Fixed. Will be in the next release.
