### ISSUE TITLE
Missing parentheses when assigned bonus points

### ISSUE THREAD

**Issue by HumanFace** [ReCodEx/web-app#487]
## Issue Description

When a solution is assigned bonus points, they are displayed as base_points + bonus_points/possible_base_points, which is missing parentheses. The right way to display it would be (base_points + bonus_points)/possible_base_points.

In the picture below it seems like the solution was assigned 4.5 points, as opposed to the actual 6/4 points.
![image](https://user-images.githubusercontent.com/13378887/216134796-dd01b72d-bb0f-43de-adcb-3b936c5a7a2b.png)

**Comment by krulis-martin** [comment]
The notation mentioned above **is not** a representation of a mathematical formula. The `/` is shorthand for `of` so it is `4+2 of 4`. The solution got 6 points, not 4.5, or 6/4 points.

Given the fact this notation has been working for over 6 years and nobody objected so far. I think changing it is more disruptive than any potential benefits, not to mention someone could really start thinking that `/` is a division.
