### ISSUE TITLE
Evaluation Details - yesterday

### ISSUE THREAD

**Issue by TomHolan** [ReCodEx/web-app#516]
## Issue Description

Page "Solution details", block "Evaluation Details" says "yesterday" - which is not true.

## Environment

Win 11, Chrome "Verze 122.0.6261.112 (Oficiální sestavení) (64bitový)"

## Steps to Reproduce

1. as a teacher select solution submitted day-before-yesterday (probably no older then 48 hours)

## Expected Behaviour

Do not show "yesterday" when it is not true.

## Actual Results

Shows "yesterday".

<img width="489" alt="240312_RCDX_yesterday" src="https://github.com/ReCodEx/web-app/assets/36609489/301a6257-8d87-4440-aadf-3b56f195f0ef">

<img width="490" alt="240312_RCDX_vcera" src="https://github.com/ReCodEx/web-app/assets/36609489/aa1b0706-cb3d-42b9-a6ba-718a130d48cf">

**Comment by krulis-martin** [comment]
All relative time notes were converted to a strictly numeric format to avoid such misunderstandings. The modification will be in the next release.
