### ISSUE TITLE
Python's input() returns CR from CRLF-files

### ISSUE THREAD

**Issue by TomHolan** [ReCodEx/web-app#519]
## Issue Description

Python's input() splits test-inputs by LF (which is natural on Linux),
but in the case when test data have other endings of lines (CRLF or CR)
it leaves CR at the end of string that input() returns
or does not split the input at all, respectively.

Maybe it is a feature, in such case would help if would be the known feature
and even in such a case it would be hard to explain to beginner programmers
why they should call .strip() or other ways to get rid of superfluous CR's. 

## Environment

Win, Chrome - does not matter.

## Steps to Reproduce

1. See task 
[https://recodex.mff.cuni.cz/app/exercises/12e48617-bade-4f1f-970c-788e12bc6cc6 ](https://recodex.mff.cuni.cz/app/exercises/12e48617-bade-4f1f-970c-788e12bc6cc6)
("Python - input() - CRLF")
2. ...and results from evaluation of its Reference solution
[https://recodex.mff.cuni.cz/app/exercises/12e48617-bade-4f1f-970c-788e12bc6cc6/reference-solution/cfa42a0e-d9bd-4938-b7d0-b1427a48c2ad](https://recodex.mff.cuni.cz/app/exercises/12e48617-bade-4f1f-970c-788e12bc6cc6/reference-solution/cfa42a0e-d9bd-4938-b7d0-b1427a48c2ad
)
3. Test Results - [Show all]
Three test inputs file have lines separated by CRLF, LF and CR.

## Expected Behaviour

Probably better: 
Input reads exactly one line, i.e. line endings of input files are changed to LF before they are passed do Python
OR (worse): 
This feature is described (maybe it already is, I have not found it) and teachers teach students, that they have to strip input()'s results.

## Actual Results

See "Steps to Reproduce"

**Comment by krulis-martin** [comment]
The exercise authors are (or should be) more than aware of the environment in which the tests are executed (and the fact we are running the workers on Linux hasn't changed since the inception of CodEx) and adjust their inputs accordingly. In this case, the expected behavior **is** that the CR character is read by input since it is present in the input file and the correction is simple, the author of the exercise should fix the source files to LF-only encoding.

Any automated modifications in ReCodEx are not advisable since they may break exercises where the exact file content is expected (this was first discussed and agreed on about 14 years ago and nothing relevant to this issue changed since then).

**Comment by TomHolan** [comment]
Dne 2024-03-22 11:50, Martin Kruliš napsal:
> The exercise authors are (or should be) more than aware of the
> environment in which the tests are executed (and the fact we are
> running the workers on Linux hasn't changed since the inception of
> CodEx) and adjust their inputs accordingly. In this case, the expected
> behavior **is** that the CR character is read by input since it is
> present in the input file and the correction is simple, the author of
> the exercise should fix the source files to LF-only encoding.
> 
> Any automated modifications in ReCodEx are not advisable since they
> may break exercises where the exact file content is expected (this was
> first discussed and agreed on about 14 years ago and nothing relevant
> to this issue changed since then).
> 
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/ReCodEx/web-app/issues/519#issuecomment-2014827353
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>


OK, dík;
hledal jsem, proč jedna studentka neprošla testem
    (u úlohy, která není moje, ale už ji zadáváme mnoho let)
a narazil jsem na tohle chování, tak jsem ho popsal.

Tom
