### ISSUE TITLE
Button leads to page I'm not able to access

### ISSUE THREAD

**Issue by mvolfik** [ReCodEx/web-app#528]
## Issue Description

A button from list of archived courses leads me to a page saying that I should report a bug.

## Steps to reproduce

I go to https://recodex.mff.cuni.cz/app/archive

![image](https://github.com/ReCodEx/web-app/assets/31281386/2485572a-ab56-4420-bbee-2f968d3eaf9f)

Click the button higlighted in red (edit done with devtools).

I get to this page:

![image](https://github.com/ReCodEx/web-app/assets/31281386/a19b011b-c3e6-467c-a1db-44e645e67e2d)

**Comment by krulis-martin** [comment]
Fixed in https://github.com/ReCodEx/web-app/pull/530, it will appear in the next release.
