### ISSUE TITLE
Cannot create account / sign-in using CAS authentication

### ISSUE THREAD

**Issue by kefik** [ReCodEx/web-app#61]
Visiting: https://recodex.ms.mff.cuni.cz/en/registration
-> Authenticate through CAS
-> credentials filled
-> CAS has accepted your credentials.
-> selected instance MFF
-> clicking on Create account
BOOM :)
On the first type I received: "Type Error"
On the second type I received: Ticket ... is not valid student or staff ...
... hmm I am lecturer for some time (Jakub Gemrot CAS num 45559095)

Cheers!

**Comment by SemaiCZE** [comment]
Can you verify the issue now? We were rebuilding the app today, so maybe you hit the unstable spot. If it doesn't help, please clear cookies and local storage for the site and try again. Thanks.

P.S.: better to use https://recodex.mff.cuni.cz

**Comment by SemaiCZE** [comment]
Oh, I can see a problem here. It's not an issue in the web-app, but it is in the api instead. Your CAS account is weird because you have multiple authorized mail addresses (as the only one we've ever seen). We'll try to fix it in the following couple of days.

**Comment by kefik** [comment]
Thanks for tracking this down!

**Comment by Neloop** [comment]
Should be fixed with https://github.com/ReCodEx/api/pull/62, which is currently deployed on testing environment. As soon as it is properly tested, it will be deployed on production.
