### ISSUE TITLE
Cannot copy-paste notifications

### ISSUE THREAD

**Issue by kefik** [ReCodEx/web-app#62]
Notifications are very nice! However I'm not able to "copy paste them" ... some icon for copy-notification-to-clipboard would be very nice feature (especially for bug reporting).

I'm on Chrome, latest version.

Cheers!

**Comment by SemaiCZE** [comment]
We are now low on frontend developers, can you please send a pull request? Thanks ;)

**Comment by kefik** [comment]
I'm sorry, my role is a mere user here... I'm low on time by default ;)

**Comment by simonrozsival** [comment]
This library could be used to implement this feature: https://github.com/nkbt/react-copy-to-clipboard
